spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*),/$\{path}
        #                        - CustomFilter

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart-service/**
          filters:
            - RewritePath=/cart-service/(?<path>.*),/$\{path}
        #                        - CustomFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*),/$\{path}
        #                        - CustomFilter

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog-service/**
          filters:
            - RewritePath=/catalog-service/(?<path>.*),/$\{path}
